### PR TITLE
Client credentials grant

### PR DESCRIPTION
**Pull request by kowalczyka**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/36)

### CODE REVIEW

**Review by GoebelL — APPROVED** [review]
> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/36)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @kowalczyka)

___
*[src/main/java/org/oscm/identity/error/DefaultExceptionHandler.java, line 60 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/36#-LoVuPIw5F2ASmLTMD_A:-LoVuPIx-aDjFVay4N73:b-4yyv40) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/cd1a48be94b11ae1c91d869e8e8fda3c563af9e6/src/main/java/org/oscm/identity/error/DefaultExceptionHandler.java#L60)):*
> ```Java
>     } catch (Exception e) {
> 
>       response =
> ```

Looks ok. I guess it's for cases with errors where json response doesn't contain error information. Ok for me, if the the fallback error message is suiteable.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/36)* status: all files reviewed, 1 unresolved discussion (waiting on @kowalczyka)

**Review by kowalczyka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/36)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[src/main/java/org/oscm/identity/error/DefaultExceptionHandler.java, line 60 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/36#-LoVuPIw5F2ASmLTMD_A:-LoZGltzCQVC-T_EYrbL:b5hkp6a) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/cd1a48be94b11ae1c91d869e8e8fda3c563af9e6/src/main/java/org/oscm/identity/error/DefaultExceptionHandler.java#L60)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Looks ok. I guess it's for cases with errors where json response doesn't contain error information. Ok for me, if the the fallback error message is suiteable.    
</blockquote></details>

Yes, exactly - we have cases where json error response looks differently

**Review by kowalczyka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/36)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[src/main/java/org/oscm/identity/error/DefaultExceptionHandler.java, line 60 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/36#-LoVuPIw5F2ASmLTMD_A:-LoZH3uf2HOUrbIjMIwe:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/cd1a48be94b11ae1c91d869e8e8fda3c563af9e6/src/main/java/org/oscm/identity/error/DefaultExceptionHandler.java#L60)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

Yes, exactly - we have cases where json error response looks differently
</blockquote></details>

Done.

**Review by GoebelL — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/36#-:-LoZUuhS0xnBYVpDbIH7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

**Review by GoebelL — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/36)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
