### PR TITLE
Feature/swagger docs for oscm identity

### LINKED ISSUE #72: Implement Swagger documentation for OSCM-IDENTITY endpoints
**Summary**
Just like *oscm-rest-api*, this module needs some API documentation. 
To be consistent, let's use Swagger for that purpose.

**Details**
N/A

**Acceptance criteria**
- [ ] oscm-identity endpoints are documented with Swagger

**Additional context**
- Spring supports Swagger quite well. There is no need for separate module (like it was in oscm-rest).

### PR DESCRIPTION
**Pull request by adamczykba**
Closes #72 

- All usable endpoints are documented.
- skipped documentation for MainController as it is used specifically for integration with existing oscm instance (@GoebelL if You find it useful to have this documented as well, let me know - I'll add it)
- skipped "Try It Out" feature for endpoints other than one for token retrieval. TBH I don't see any real value in keeping it (@GoebelL what is Your opinion?). There were also some difficulties with configuring it to work with bearer token which I couldn't overcome

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/88)

### CODE REVIEW

**Comment by GoebelL** [comment]
>     * skipped documentation for MainController as it is used specifically for integration with existing oscm instance (@GoebelL if You find it useful to have this documented as well, let me know - I'll add it)
> 

Ok, skip that. 

>     * skipped "Try It Out" feature for endpoints other than one for token retrieval. TBH I don't see any real value in keeping it (@GoebelL what is Your opinion?). There were also some difficulties with configuring it to work with bearer token which I couldn't overcome
> 

Dito.

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 5 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/88)* status: 5 of 11 files reviewed, 1 unresolved discussion (waiting on @adamczykba, @GoebelL, and @kowalczyka)

___
*[src/main/resources/tenant-default.properties, line 3 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/88#-Ly3V4__26aa35oDWrRb:-Ly3V4_a06AQABoRX24I:b-4prli4) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/d3bd3c6f89d8b86bb9643f628174271fdd9ac16f/src/main/resources/tenant-default.properties#L3)):*
> ```INI
> oidc.provider=default
> oidc.clientId=5d8e73ec-8802-4056-a557-c1911691c781
> oidc.clientSecret=dd1GR.86qwRp.evIv8YGUwUAYbnR--l=
> ```

Are these settings realy needed here? For documentation?
Feels wrong for me having to maintain these in two files,  oscm-identity/config/tenants/tenant-default.properties and this one.
___
*[src/main/resources/tenant-default.properties, line 8 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/88#-Ly3Vw128AL_A_VCBmAu:-Ly3Vw128AL_A_VCBmAv:brdr29o) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/d3bd3c6f89d8b86bb9643f628174271fdd9ac16f/src/main/resources/tenant-default.properties#L8)):*
> ```INI
> oidc.logoutUrl=https://login.microsoftonline.com/ctmgsso.onmicrosoft.com/oauth2/v2.0/logout
> oidc.tokenUrl=https://login.microsoftonline.com/ctmgsso.onmicrosoft.com/oauth2/v2.0/token
> oidc.redirectUrl=http://localhost:9090/oscm-identity/callback
> ```

Btw, always state https URLs - no unsecure http, regardless if it's a documentation example.

**Review by adamczykba — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/88)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @kowalczyka)

___
*[src/main/resources/tenant-default.properties, line 3 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/88#-Ly3V4__26aa35oDWrRb:-Ly3ZwFt7YvIxA2EkuwH:bmj7m77) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/d3bd3c6f89d8b86bb9643f628174271fdd9ac16f/src/main/resources/tenant-default.properties#L3)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Are these settings realy needed here? For documentation?
Feels wrong for me having to maintain these in two files,  oscm-identity/config/tenants/tenant-default.properties and this one.
</blockquote></details>

Good catch actually. It's only my local config. It must have slip through by mistake. Fixed this though
___
*[src/main/resources/tenant-default.properties, line 8 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/88#-Ly3Vw128AL_A_VCBmAu:-Ly3_4km-LOQD_I34ajx:bs4q9op) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/d3bd3c6f89d8b86bb9643f628174271fdd9ac16f/src/main/resources/tenant-default.properties#L8)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Btw, always state https URLs - no unsecure http, regardless if it's a documentation example.
</blockquote></details>

Ditto.

**Review by GoebelL — APPROVED** [review]
> Reviewed 5 of 11 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/88)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kowalczyka)

**Pull request merged**
