### PR TITLE
Task/implement access token validation call

### PR DESCRIPTION
**Pull request by adamczykba**
This PR is a part of https://github.com/servicecatalog/oscm/issues/417

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/34)

### CODE REVIEW

**Review by kowalczyka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/34)* status: 0 of 20 files reviewed, 13 unresolved discussions (waiting on @adamczykba, @Crystalzord, and @kowalczyka)

___
*[src/main/java/org/oscm/identity/controller/MainController.java, line 210 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZlajL5kD9LXCZD22_:-LoZlajL5kD9LXCZD22a:b-owtx0t) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/controller/MainController.java#L210)):*
> ```Java
>    * @return HTTP Response
>    */
>   @PostMapping(value = "/verify_token")
> ```

Could we move tenantId information from TokenValidationRequest to path param (similary to other endpoints e.g. UserController/GroupController)?

Decoded tokens are not a part of request. Maybe it would be better to move them to validator class.

Additionally maybe it would nicer to accept the request which contains only one token information i.e {"token":"", "type":""} and based on type validates against specific strategies.
___
*[src/main/java/org/oscm/identity/controller/MainController.java, line 216 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZmZX4DwD75ct6yHmB:-LoZmZX4DwD75ct6yHmC:bc4jc77) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/controller/MainController.java#L216)):*
> ```Java
>     if (validationResult.isValid()) return ResponseEntity.ok(TOKEN_VALID_MESSAGE);
>     else
>       return ResponseEntity.status(HttpStatus.NOT_ACCEPTABLE)
> ```

Please use DefaultExceptionHandler so that every error response has the same format ( see ErrorResponse object).
___
*[src/main/java/org/oscm/identity/oidc/validation/AuthTokenValidator.java, line 36 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZoV2QDkVTNyrvzWbz:-LoZoV2R8sa-_EB2t0Ad:b-k4e6uu) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/AuthTokenValidator.java#L36)):*
> ```Java
> 
>   @Autowired
>   public AuthTokenValidator(
> ```

Let's consider splitting this into separate validator for different tokens.
___
*[src/main/java/org/oscm/identity/oidc/validation/AuthTokenValidator.java, line 93 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZonOU-5TtItlzcSzA:-LoZonOU-5TtItlzcSzB:bgtwipf) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/AuthTokenValidator.java#L93)):*
> ```Java
>    * @return Token Validation Request with decoded tokens
>    * @throws JWTDecodeException
>    */
> ```

As already mentioned, decoded tokens are not part of the request.
___
*[src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenAlgorithmValidationStrategy.java, line 31 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZp_aU8oGkOSfd9avd:-LoZp_aU8oGkOSfd9ave:b-7ropln) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenAlgorithmValidationStrategy.java#L31)):*
> ```Java
> 
>     if (!request.getDecodedIdToken().getAlgorithm().equalsIgnoreCase(expectedAlgorithmType))
>       throw new ValidationException(getFailureMessage());
> ```

ditto
___
*[src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenExpirationTimeValidationStrategy.java, line 34 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZpgW5-Nc36YzJKSeD:-LoZpgW5-Nc36YzJKSeE:b-7ropln) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenExpirationTimeValidationStrategy.java#L34)):*
> ```Java
>     if (LocalDateTime.now()
>         .isAfter(convertDateToLocalDateTime(request.getDecodedIdToken().getExpiresAt())))
>       throw new ValidationException(getFailureMessage());
> ```

ditto
___
*[src/main/java/org/oscm/identity/oidc/validation/strategy/AccessTokenAlgorithmValidationStrategy.java, line 34 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZp8qBBqN4im8z_CtB:-LoZp8qBBqN4im8z_CtC:b-1fyv1a) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/strategy/AccessTokenAlgorithmValidationStrategy.java#L34)):*
> ```Java
> 
>     if (!request.getDecodedAccessToken().getAlgorithm().equalsIgnoreCase(expectedAlgorithmType))
>       throw new ValidationException(getFailureMessage());
> ```

Consider creating new TokenValidationException which could be handled in DefaultExceptionHandler
___
*[src/main/java/org/oscm/identity/oidc/validation/strategy/AccessTokenExpirationTimeValidationStrategy.java, line 34 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZpV8N8wEjD-8AdMXl:-LoZpV8N8wEjD-8AdMXm:b-7ropln) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/strategy/AccessTokenExpirationTimeValidationStrategy.java#L34)):*
> ```Java
>     if (LocalDateTime.now()
>         .isAfter(convertDateToLocalDateTime(request.getDecodedAccessToken().getExpiresAt())))
>       throw new ValidationException(getFailureMessage());
> ```

ditto
___
*[src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenAudienceValidationStrategy.java, line 45 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZpeDf7Tj7zCv22fYj:-LoZpeDf7Tj7zCv22fYk:b-7ropln) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenAudienceValidationStrategy.java#L45)):*
> ```Java
> 
>     if (!request.getDecodedIdToken().getAudience().contains(tenantConfiguration.getClientId()))
>       throw new ValidationException(getFailureMessage());
> ```

ditto
___
*[src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenISSValidationStrategy.java, line 51 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZpzIN6tNYl1sEU2-L:-LoZpzIN6tNYl1sEU2-M:b-7ropln) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenISSValidationStrategy.java#L51)):*
> ```Java
>       String issuer = getIssuerFromRemoteConfig(tenantConfiguration.getConfigurationUrl());
>       if (!issuer.equals(request.getDecodedIdToken().getIssuer()))
>         throw new ValidationException(getFailureMessage());
> ```

ditto
___
*[src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenISSValidationStrategy.java, line 53 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZq-DHAPj4hF6hnLpd:-LoZq-DHAPj4hF6hnLpe:b-7ropln) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenISSValidationStrategy.java#L53)):*
> ```Java
>         throw new ValidationException(getFailureMessage());
>     } catch (JSONException e) {
>       throw new ValidationException(e.getMessage());
> ```

ditto
___
*[src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenNonceValidationStrategy.java, line 22 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZq697B1fPUZtpcri_:-LoZq697B1fPUZtpcria:bmvhzru) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenNonceValidationStrategy.java#L22)):*
> ```Java
> public class IdTokenNonceValidationStrategy extends TokenValidationStrategy {
> 
>   //FIXME: Nonce is not properly implemented yet
> ```

Let's add nonce to tenant configuration and validate token nonce against it
___
*[src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenNonceValidationStrategy.java, line 27 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZq22m2WTbLLO0LiG0:-LoZq22m2WTbLLO0LiG1:b-1fyv1a) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenNonceValidationStrategy.java#L27)):*
> ```Java
>     if (request.getNonce() != null) {
>       if (!request.getNonce().equals(request.getDecodedIdToken().getClaim("nonce").asString()))
>         throw new ValidationException(getFailureMessage());
> ```

Consider creating new TokenValidationException which could be handled in DefaultExceptionHandler

**Review by adamczykba — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/34)* status: 0 of 20 files reviewed, 13 unresolved discussions (waiting on @Crystalzord and @kowalczyka)

___
*[src/main/java/org/oscm/identity/controller/MainController.java, line 210 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZlajL5kD9LXCZD22_:-LoZyQAa-KxRGEdBa2MS:bkqxxbl) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/controller/MainController.java#L210)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

Could we move tenantId information from TokenValidationRequest to path param (similary to other endpoints e.g. UserController/GroupController)?

Decoded tokens are not a part of request. Maybe it would be better to move them to validator class.

Additionally maybe it would nicer to accept the request which contains only one token information i.e {"token":"", "type":""} and based on type validates against specific strategies.
</blockquote></details>

Ad 1: It will be done in scope of oscm-identity#37
Ad 2 and 3: It will be done in scope of oscm-identity#38
___
*[src/main/java/org/oscm/identity/controller/MainController.java, line 216 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZmZX4DwD75ct6yHmB:-LoZyxtA4YRLaHdQ3Kkt:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/controller/MainController.java#L216)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

Please use DefaultExceptionHandler so that every error response has the same format ( see ErrorResponse object).
</blockquote></details>

Done.
___
*[src/main/java/org/oscm/identity/oidc/validation/AuthTokenValidator.java, line 36 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZoV2QDkVTNyrvzWbz:-LoZygce7YXZRsp8fE71:b-bzusp6) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/AuthTokenValidator.java#L36)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

Let's consider splitting this into separate validator for different tokens.
</blockquote></details>

It will be covered in scope of oscm-identity#38
___
*[src/main/java/org/oscm/identity/oidc/validation/AuthTokenValidator.java, line 93 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZonOU-5TtItlzcSzA:-LoZymcI9_C6fXiQcRdg:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/AuthTokenValidator.java#L93)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

As already mentioned, decoded tokens are not part of the request.
</blockquote></details>

Done.
___
*[src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenAlgorithmValidationStrategy.java, line 31 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZp_aU8oGkOSfd9avd:-LoZyqyV3a3vnyG0TQ_I:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenAlgorithmValidationStrategy.java#L31)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenExpirationTimeValidationStrategy.java, line 34 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZpgW5-Nc36YzJKSeD:-LoZysAR8vQorzPDEBNw:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenExpirationTimeValidationStrategy.java#L34)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[src/main/java/org/oscm/identity/oidc/validation/strategy/AccessTokenAlgorithmValidationStrategy.java, line 34 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZp8qBBqN4im8z_CtB:-LoZypTTCixUZALpBEYi:b6jnrjg) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/strategy/AccessTokenAlgorithmValidationStrategy.java#L34)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

Consider creating new TokenValidationException which could be handled in DefaultExceptionHandler
</blockquote></details>

It will be done in scope of oscm-identity#38
___
*[src/main/java/org/oscm/identity/oidc/validation/strategy/AccessTokenExpirationTimeValidationStrategy.java, line 34 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZpV8N8wEjD-8AdMXl:-LoZyqIi5cp2TjfgmkVI:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/strategy/AccessTokenExpirationTimeValidationStrategy.java#L34)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenAudienceValidationStrategy.java, line 45 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZpeDf7Tj7zCv22fYj:-LoZyrg57DD5Lt_nMucK:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenAudienceValidationStrategy.java#L45)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenISSValidationStrategy.java, line 51 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZpzIN6tNYl1sEU2-L:-LoZysgB9CyEgTVQl6PR:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenISSValidationStrategy.java#L51)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenISSValidationStrategy.java, line 53 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZq-DHAPj4hF6hnLpd:-LoZyt-O1DLyfx5usqYg:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenISSValidationStrategy.java#L53)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenNonceValidationStrategy.java, line 22 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZq697B1fPUZtpcri_:-LoZyv7YB-YPmzI6s2WN:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenNonceValidationStrategy.java#L22)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

Let's add nonce to tenant configuration and validate token nonce against it
</blockquote></details>

Done.
___
*[src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenNonceValidationStrategy.java, line 27 at r4](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-LoZq22m2WTbLLO0LiG0:-LoZyvaDACoAPVvhRElB:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/2f488f3cd112b439425430fa7d1e773cef2839eb/src/main/java/org/oscm/identity/oidc/validation/strategy/IdTokenNonceValidationStrategy.java#L27)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

Consider creating new TokenValidationException which could be handled in DefaultExceptionHandler
</blockquote></details>

Done.

**Review by kowalczyka — APPROVED** [review]
LGTM

> Reviewed 18 of 20 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-:-LoeW4V10VmjpZgAiTW-:bb6ywmx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Crystalzord)

**Review by kowalczyka — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-:-Loe_OEKCp1wxqM4f6Rb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Crystalzord)

**Review by adamczykba — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/34#-:-Losluhr-9k0i7duEnpX:bnfp4nl)* status: 9 of 31 files reviewed, all discussions resolved (waiting on @Crystalzord and @kowalczyka)

**Pull request merged**
