### PR TITLE
Create group endpoint

### PR DESCRIPTION
**Pull request by kowalczyka**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/29)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 46 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/29)* status: 46 of 47 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @kowalczyka)

___
*[src/main/java/org/oscm/identity/error/IdentityProviderException.java, line 5 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/29#-Lm4y6Bq0AEqHRkmXALh:-Lm4y6Bq0AEqHRkmXALi:b-ciom1o) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/7498cdd78ed463674dc9ceb1f255731b10b27594/src/main/java/org/oscm/identity/error/IdentityProviderException.java#L5)):*
> ```Java
> public class IdentityProviderException extends RuntimeException{
> 
>     private String error;
> ```

Unused?

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/29)* status: all files reviewed, 1 unresolved discussion (waiting on @kowalczyka)

**Review by kowalczyka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/29)* status: 46 of 47 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[src/main/java/org/oscm/identity/error/IdentityProviderException.java, line 5 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/29#-Lm4y6Bq0AEqHRkmXALh:-Lm8k7IzAUR6TGFygigQ:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/7498cdd78ed463674dc9ceb1f255731b10b27594/src/main/java/org/oscm/identity/error/IdentityProviderException.java#L5)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Unused?
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/29)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
