### PR TITLE
Implement refresh endpoint for refreshing access token.

### PR DESCRIPTION
**Pull request by Crystalzord**
In this PR:
- Added POST /refresh endpoint that required JSON object with 3 fields: scope, refreshToken and grantType. It refreshes access token using refreshToken and redirects with the new accessToken and refreshToken to the state.

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/32)

### CODE REVIEW

**Review by adamczykba — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/32)* status: all files reviewed, 8 unresolved discussions (waiting on @Crystalzord and @kowalczyka)

___
*[src/main/java/org/oscm/identity/controller/MainController.java, line 142 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/32#-Lo5RXdVBQGqe0k5pkk8:-Lo5RXdWAO5t4BIVuNpk:b6k2qpb) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/e1e07cc87571b35f5ce5d83447d08cdcd40ba95d/src/main/java/org/oscm/identity/controller/MainController.java#L142)):*
> ```Java
>       throws JSONException, ValidationException, IOException {
> 
>     if (refreshBody.getRefreshToken() == null
> ```

This is already covered inside RefreshBody itself (@NotNull annotation)
___
*[src/main/java/org/oscm/identity/controller/MainController.java, line 144 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/32#-Lo5RgsY1vJ4CJM6Ocbr:-Lo5RgsY1vJ4CJM6Ocbs:blyty4v) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/e1e07cc87571b35f5ce5d83447d08cdcd40ba95d/src/main/java/org/oscm/identity/controller/MainController.java#L144)):*
> ```Java
>     if (refreshBody.getRefreshToken() == null
>         || refreshBody.getGrantType() == null
>         || refreshBody.getState() == null) {
> ```

Move this check to RefreshBody itself
___
*[src/main/java/org/oscm/identity/controller/RefreshBody.java, line 1 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/32#-Lo5S2tr4bKUCJ78-aJl:-Lo5S2tr4bKUCJ78-aJm:bec9vfn) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/e1e07cc87571b35f5ce5d83447d08cdcd40ba95d/src/main/java/org/oscm/identity/controller/RefreshBody.java#L1)):*
> ```Java
> package org.oscm.identity.controller;
> ```

Copyright clause is missing
___
*[src/main/java/org/oscm/identity/controller/RefreshBody.java, line 8 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/32#-Lo5S8rJ5anSM-xf80Gk:-Lo5S8rJ5anSM-xf80Gl:bv0926v) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/e1e07cc87571b35f5ce5d83447d08cdcd40ba95d/src/main/java/org/oscm/identity/controller/RefreshBody.java#L8)):*
> ```Java
> 
> @Data
> public class RefreshBody {
> ```

Javadoc missing
___
*[src/main/java/org/oscm/identity/oidc/request/DefaultRefreshRequest.java, line 20 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/32#-Lo5SEux9yr2063MIkZ4:-Lo5SEux9yr2063MIkZ5:b-nnm6u9) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/e1e07cc87571b35f5ce5d83447d08cdcd40ba95d/src/main/java/org/oscm/identity/oidc/request/DefaultRefreshRequest.java#L20)):*
> ```Java
> import org.springframework.web.client.RestTemplate;
> 
> public class DefaultRefreshRequest extends RefreshRequest {
> ```

Javadoc is missing
___
*[src/main/java/org/oscm/identity/oidc/request/DefaultRefreshRequest.java, line 34 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/32#-Lo5SP075HEnti00gdgI:-Lo5SP081xVdueUSaJG3:b-b43494) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/e1e07cc87571b35f5ce5d83447d08cdcd40ba95d/src/main/java/org/oscm/identity/oidc/request/DefaultRefreshRequest.java#L34)):*
> ```Java
>     headers.setContentType(MediaType.APPLICATION_FORM_URLENCODED);
> 
>     MultiValueMap<String, String> map = new LinkedMultiValueMap<>();
> ```

Is there a reason why this kind of map is used insteac HashMap?
___
*[src/test/java/org/oscm/identity/controller/MainControllerTest.java, line 215 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/32#-Lo5Sut_An5P9Itwak_J:-Lo5Sut_An5P9Itwak_K:b41myae) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/e1e07cc87571b35f5ce5d83447d08cdcd40ba95d/src/test/java/org/oscm/identity/controller/MainControllerTest.java#L215)):*
> ```Java
>   public void shouldRedirectToHomeWithToken_whenPostToRefreshToken_givenNoErrors() {
>     TenantConfiguration configuration = new TenantConfiguration();
>     configuration.setProvider("default");
> ```

Tenant Configuration can be as well fetched from testresources (see other simillar test cases)
___
*[src/test/java/org/oscm/identity/controller/MainControllerTest.java, line 249 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/32#-Lo5TDzc2-AXJ9d-b6xG:-Lo5TDzc2-AXJ9d-b6xH:b-89a4l7) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/e1e07cc87571b35f5ce5d83447d08cdcd40ba95d/src/test/java/org/oscm/identity/controller/MainControllerTest.java#L249)):*
> ```Java
>         TokenValidationResult.of().isValid(false).validationFailureReason("Reason").build();
> 
>     TenantConfiguration configuration = new TenantConfiguration();
> ```

Ditto

**Review by adamczykba — COMMENTED** [review]
Also let's keep code coverage at level of 80% or above

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/32#-:-Lo5T_Bx3c3-Dwsta3AA:bmx01y)* status: all files reviewed, 8 unresolved discussions (waiting on @Crystalzord and @kowalczyka)

**Review by Crystalzord — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/32)* status: 5 of 9 files reviewed, 8 unresolved discussions (waiting on @adamczykba and @kowalczyka)

___
*[src/main/java/org/oscm/identity/controller/MainController.java, line 142 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/32#-Lo5RXdVBQGqe0k5pkk8:-LoKhWl17d9z8dyNx26G:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/e1e07cc87571b35f5ce5d83447d08cdcd40ba95d/src/main/java/org/oscm/identity/controller/MainController.java#L142)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

This is already covered inside RefreshBody itself (@NotNull annotation)
</blockquote></details>

Done.
___
*[src/main/java/org/oscm/identity/controller/MainController.java, line 144 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/32#-Lo5RgsY1vJ4CJM6Ocbr:-LoKhX3q3SctnCyD-X0t:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/e1e07cc87571b35f5ce5d83447d08cdcd40ba95d/src/main/java/org/oscm/identity/controller/MainController.java#L144)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

Move this check to RefreshBody itself
</blockquote></details>

Done.
___
*[src/main/java/org/oscm/identity/oidc/request/DefaultRefreshRequest.java, line 20 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/32#-Lo5SEux9yr2063MIkZ4:-LoKhXdH4qf2IDqtlZIo:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/e1e07cc87571b35f5ce5d83447d08cdcd40ba95d/src/main/java/org/oscm/identity/oidc/request/DefaultRefreshRequest.java#L20)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

Javadoc is missing
</blockquote></details>

Done.
___
*[src/main/java/org/oscm/identity/oidc/request/DefaultRefreshRequest.java, line 34 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/32#-Lo5SP075HEnti00gdgI:-LoKhY9U4j9F5TtJsyZ0:b-93vx31) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/e1e07cc87571b35f5ce5d83447d08cdcd40ba95d/src/main/java/org/oscm/identity/oidc/request/DefaultRefreshRequest.java#L34)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

Is there a reason why this kind of map is used insteac HashMap?
</blockquote></details>

To stay consistent with other classes
___
*[src/test/java/org/oscm/identity/controller/MainControllerTest.java, line 215 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/32#-Lo5Sut_An5P9Itwak_J:-LoL3bi5EBUdF-5JNDOe:b5r3w29) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/e1e07cc87571b35f5ce5d83447d08cdcd40ba95d/src/test/java/org/oscm/identity/controller/MainControllerTest.java#L215)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

Tenant Configuration can be as well fetched from testresources (see other simillar test cases)
</blockquote></details>

I want to be consistent with the class
___
*[src/test/java/org/oscm/identity/controller/MainControllerTest.java, line 249 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/32#-Lo5TDzc2-AXJ9d-b6xG:-LoL3cQv8u3i3ymQjQKz:b5r3w29) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/e1e07cc87571b35f5ce5d83447d08cdcd40ba95d/src/test/java/org/oscm/identity/controller/MainControllerTest.java#L249)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

I want to be consistent with the class
___
*[src/main/java/org/oscm/identity/controller/RefreshBody.java, line 1 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/32#-Lo5S2tr4bKUCJ78-aJl:-LoKh_7v-x3iDpJfjH0f:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/e1e07cc87571b35f5ce5d83447d08cdcd40ba95d/src/main/java/org/oscm/identity/controller/RefreshBody.java#L1)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

Copyright clause is missing
</blockquote></details>

Done.
___
*[src/main/java/org/oscm/identity/controller/RefreshBody.java, line 8 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/32#-Lo5S8rJ5anSM-xf80Gk:-LoKh_wQDoefv1rVQfwX:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/e1e07cc87571b35f5ce5d83447d08cdcd40ba95d/src/main/java/org/oscm/identity/controller/RefreshBody.java#L8)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

Javadoc missing
</blockquote></details>

Done.

**Review by adamczykba — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/32#-:-LoL5Dp0BCKCFJZisTgf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kowalczyka)

**Pull request merged**
