### PR TITLE
Group not found error logging is now optional

### LINKED ISSUE #66: Suppress logging for expected exception
**Summary**
In some cases, queries to oscm-identity are required that might fail. In case when such probes are handled by the client, it is not desired to find error traces in the logs.

**Details**
For example, when registering an organization, OSCM attempts to query a respective access group in the OIDC provider. This query is expected to fail, if no matching group can be found. In consequnce the group is created with a subsequent request. The first request should be silent. 

Therefore oscm-identiy should provide for supressing exception logging on demand. 
A viable solution here could be to add an optional flag for this endpoint in form of some request parameter which skips the error logging for this particular request.

**Acceptance criteria**
- [ ] The find access group operation does not log errors if no group was found (maybe just on demand, as described above)

**Additional context**
Currently following error is logged _everytime_ when creating an organization or registering a customer in OSCM, even when this is eventually successful: 
``` 
2019-10-29 18:02:03.541 ERROR 49 --- [nio-9090-exec-6] o.o.i.error.DefaultExceptionHandler      : Group of requested name has not been found
com.jayway.jsonpath.JsonPathException: Group of requested name has not been found
at org.oscm.identity.model.response.DefaultResponseMapper.lambda$getGroup$1(DefaultResponseMapper.java:91) ~[classes!/:1.0-SNAPSHOT]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_232]
        ... (many lines more)
```

### PR DESCRIPTION
**Pull request by adamczykba**
**Changes in this Pull Request:**
- exception logging when getting the groups is now optional. This functionality can be configured either globally - in ``application.properties`` file and locally - by adding ``?logErrors=true`` query parameter to the GET request.

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] changes were tested manually
- [x] unit tests were properly implemented
- [x] communication about interdependent changes has been sent to the team (if applicable)
- [x] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
N/A

Closes #66 

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/73)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/73)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @adamczykba, @GoebelL, and @kowalczyka)

___
*[src/main/resources/application.properties, line 6 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/73#-Lt54JG-BXtQhrpB_k5w:-Lt54JG-BXtQhrpB_k5x:b-dbo2ze) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/d438ea4f06bbd21035de57fec3165da1fcd9a7ec/src/main/resources/application.properties#L6)):*
> ```INI
> http.port=9090
> 
> system.log.errors=true
> ```

Since it's a very specific case I'd suggest to simply hard code the default with "true" and drop this setting here.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/73)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @adamczykba, @GoebelL, and @kowalczyka)

**Review by adamczykba — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/73)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @kowalczyka)

___
*[src/main/resources/application.properties, line 6 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/73#-Lt54JG-BXtQhrpB_k5w:-Lt5NuHkCaBWVX8cHB_6:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/d438ea4f06bbd21035de57fec3165da1fcd9a7ec/src/main/resources/application.properties#L6)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Since it's a very specific case I'd suggest to simply hard code the default with "true" and drop this setting here. 
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/73)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kowalczyka)

**Pull request merged**
