### PR TITLE
Auth code flow and user info endpoint

### PR DESCRIPTION
**Pull request by kowalczyka**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/22)

### CODE REVIEW

**Review by adamczykba — CHANGES_REQUESTED** [review]
> Reviewed 37 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/22)* status: all files reviewed, 6 unresolved discussions (waiting on @kowalczyka)

___
*[pom.xml, line 60 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/22#-Ll6NpwK4aDgKO0gt2xc:-Ll6NpwL3PNN3NBu5rVh:b-u50ek7) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/96f177b46a39b6991c54c50bd3c15bb9ff24a756/pom.xml#L60)):*
> ```XML
>             <groupId>org.apache.httpcomponents</groupId>
>             <artifactId>httpclient</artifactId>
>             <version>4.5.9</version>
> ```

Wouldn't it be better to keep the versions in pom properties, just like with all other dependencies?
___
*[src/main/java/org/oscm/identity/controller/MainController.java, line 87 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/22#-Ll6Q7XACVGImsN9Xh0t:-Ll6Q7XACVGImsN9Xh0u:bqtq0ig) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/96f177b46a39b6991c54c50bd3c15bb9ff24a756/src/main/java/org/oscm/identity/controller/MainController.java#L87)):*
> ```Java
>     }
> 
>     log.debug("Authorization code retrieved:" + code);
> ```

Should we log this as a debug? Maybe info would suffice?
___
*[src/main/java/org/oscm/identity/controller/MainController.java, line 107 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/22#-Ll6Q9OgCBrlXGl9B1P-:-Ll6Q9OgCBrlXGl9B1P0:b-89a4l7) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/96f177b46a39b6991c54c50bd3c15bb9ff24a756/src/main/java/org/oscm/identity/controller/MainController.java#L107)):*
> ```Java
>     String refreshToken = jsonResponse.get("refresh_token").toString();
> 
>     log.debug("Access token received:" + accessToken);
> ```

Ditto
___
*[src/main/java/org/oscm/identity/controller/MainController.java, line 121 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/22#-Ll6QAR_BhgQzt1ItDHW:-Ll6QAR_BhgQzt1ItDHX:b-89a4l7) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/96f177b46a39b6991c54c50bd3c15bb9ff24a756/src/main/java/org/oscm/identity/controller/MainController.java#L121)):*
> ```Java
>               .toString();
> 
>       log.debug("Redirecting to " + url);
> ```

Ditto
___
*[src/main/java/org/oscm/identity/oidc/response/validation/ISSValidationStrategy.java, line 72 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/22#-Ll702y6-KNNGOw_coSN:-Ll702y6-KNNGOw_coSO:b-vllux6) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/96f177b46a39b6991c54c50bd3c15bb9ff24a756/src/main/java/org/oscm/identity/oidc/response/validation/ISSValidationStrategy.java#L72)):*
> ```Java
>     RestTemplate restTemplate = new RestTemplate();
> 
>     if (Boolean.valueOf(proxyHandler.isRequired())) {
> ```

Proxy enablement for resttemplate should be handled more globally. In current solution, every time when we would want to use rest remplate we will have to provide this 'if'. Maybe place it in a bean configuration?
___
*[src/main/java/org/oscm/identity/service/BeanUtil.java, line 21 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/22#-Ll76K_D3s-CJMJruN05:-Ll76K_H6s5K0atxwbEi:bgvxmqy) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/96f177b46a39b6991c54c50bd3c15bb9ff24a756/src/main/java/org/oscm/identity/service/BeanUtil.java#L21)):*
> ```Java
>  */
> @Service
> public class BeanUtil implements ApplicationContextAware {
> ```

Investigate wether it's possible to use built-in spring functionality for retrieving the beans. Let's try to work with spring - not against it

**Review by kowalczyka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/22)* status: 20 of 40 files reviewed, 6 unresolved discussions (waiting on @adamczykba)

___
*[pom.xml, line 60 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/22#-Ll6NpwK4aDgKO0gt2xc:-LlVmV7H4BCiZ8Qfft90:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/96f177b46a39b6991c54c50bd3c15bb9ff24a756/pom.xml#L60)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

Wouldn't it be better to keep the versions in pom properties, just like with all other dependencies?
</blockquote></details>

Done.
___
*[src/main/java/org/oscm/identity/controller/MainController.java, line 87 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/22#-Ll6Q7XACVGImsN9Xh0t:-LlVmcqQ4MtPpXj3Np-m:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/96f177b46a39b6991c54c50bd3c15bb9ff24a756/src/main/java/org/oscm/identity/controller/MainController.java#L87)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

Should we log this as a debug? Maybe info would suffice?
</blockquote></details>

Done.
___
*[src/main/java/org/oscm/identity/controller/MainController.java, line 107 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/22#-Ll6Q9OgCBrlXGl9B1P-:-LlVmdq38sClTT5Cz8pu:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/96f177b46a39b6991c54c50bd3c15bb9ff24a756/src/main/java/org/oscm/identity/controller/MainController.java#L107)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/java/org/oscm/identity/controller/MainController.java, line 121 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/22#-Ll6QAR_BhgQzt1ItDHW:-LlVmeUe1W8Y8u6l5xh-:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/96f177b46a39b6991c54c50bd3c15bb9ff24a756/src/main/java/org/oscm/identity/controller/MainController.java#L121)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/java/org/oscm/identity/oidc/response/validation/ISSValidationStrategy.java, line 72 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/22#-Ll702y6-KNNGOw_coSN:-LlVn78e7CpZtrVQZXEH:bmksnmu) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/96f177b46a39b6991c54c50bd3c15bb9ff24a756/src/main/java/org/oscm/identity/oidc/response/validation/ISSValidationStrategy.java#L72)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

Proxy enablement for resttemplate should be handled more globally. In current solution, every time when we would want to use rest remplate we will have to provide this 'if'. Maybe place it in a bean configuration?
</blockquote></details>

This is moved now to configuration class (RestTemplate bean).
___
*[src/main/java/org/oscm/identity/service/BeanUtil.java, line 21 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/22#-Ll76K_D3s-CJMJruN05:-LlVnQ4J4uyznP2eN7Pv:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/96f177b46a39b6991c54c50bd3c15bb9ff24a756/src/main/java/org/oscm/identity/service/BeanUtil.java#L21)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

Investigate wether it's possible to use built-in spring functionality for retrieving the beans. Let's try to work with spring - not against it
</blockquote></details>

Done.

**Review by kowalczyka — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/22#-:-LlVn_AcBkDWR0laUnlx:b-896fix)* status: 20 of 40 files reviewed, 6 unresolved discussions (waiting on @adamczykba)

**Review by adamczykba — DISMISSED** [review]
Everything is just fine, aside from significant drop in code coverage

> Reviewed 21 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/22#-:-LlVuNBE93lSJHOr_FAk:bak0ju)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Crystalzord — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/22)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
