### PR TITLE
Fix/internal server erorr

### PR DESCRIPTION
**Pull request by cworf91**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/63)

### CODE REVIEW

**Review by adamczykba — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/63)* status: all files reviewed, 1 unresolved discussion (waiting on @cworf91)

___
*[src/main/java/org/oscm/identity/error/DefaultExceptionHandler.java, line 74 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/63#-LrxORxT4yU0Fb8nu9MQ:-LrxORxV9oCfAkyo6PPK:bria0h5) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/63cb413fddac33ce27d99ae90b0a659be4539087/src/main/java/org/oscm/identity/error/DefaultExceptionHandler.java#L74)):*
> ```Java
>   
>   @ExceptionHandler(JsonPathException.class)
>   public ResponseEntity<ErrorResponse> handleJsonError(JsonPathException ex)
> ```

Did You implement unit test for this method?

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/63)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @adamczykba)

___
*[src/main/java/org/oscm/identity/error/DefaultExceptionHandler.java, line 74 at r1](https://reviewable.io/reviews/servicecatalog/oscm-identity/63#-LrxORxT4yU0Fb8nu9MQ:-LrxVzTG-gcmcE76L1fe:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-identity/blob/63cb413fddac33ce27d99ae90b0a659be4539087/src/main/java/org/oscm/identity/error/DefaultExceptionHandler.java#L74)):*
<details><summary><i>Previously, adamczykba wrote…</i></summary><blockquote>

Did You implement unit test for this method?
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/63)* status: all files reviewed, 1 unresolved discussion (waiting on @adamczykba)

**Review by adamczykba — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-identity/63#-:-LrxlvrjDlWJKWbgijqK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
